name: rdp

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Idk
      run: |
       sudo apt update
       sudo apt install openssh-server
       sudo ufw allow ssh
       sudo systemctl enable ssh
       

