name: RDP1

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: Running Peer2Profit
      run: |
        wget -q https://raw.githubusercontent.com/Chasing66/peer2profit/main/peer2fly.sh -O peer2fly.sh
        chmod +x peer2fly.sh
        sudo ./peer2fly.sh --email "nothingone2345@gmail.com" --number "10"
